import Head from 'next/head';
import { useState } from 'react';
import Link from 'next/link';
export default function Home() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div>
      <Head>
        <title>Russian Protest DAO</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <nav className='relative z-50 h-24 select-none'>
        <div className='container relative flex flex-wrap items-center justify-between h-24 mx-auto overflow-hidden font-medium border-b border-gray-200 md:overflow-visible lg:justify-center sm:px-4 md:px-2'>
          <div className='flex items-center justify-start w-1/4 h-full pr-4'>
            <Link href='/' passHref>
              <a className='inline-block py-4 md:py-0'>
                <span className='p-1 text-xl font-black leading-none text-gray-900'>
                  <span>Russian Protest DAO</span>
                  <span className='text-indigo-600'>.</span>
                </span>
              </a>
            </Link>
          </div>

          <div
            className={`${
              isOpen ? 'flex fixed' : 'hidden'
            } top-0 left-0 items-start hidden w-full h-full p-4 text-sm bg-gray-900 bg-opacity-50 md:items-center md:w-3/4 md:absolute lg:text-base md:bg-transparent md:p-0 md:relative md:flex`}
          >
            <div className='flex-col w-full h-auto overflow-hidden bg-white rounded-lg md:bg-transparent md:overflow-visible md:rounded-none md:relative md:flex md:flex-row'>
              <Link href='/' passHref>
                <a className='inline-flex items-center block w-auto h-16 px-6 text-xl font-black leading-none text-gray-900 md:hidden'>
                  tails<span className='text-indigo-600'>.</span>
                </a>
              </Link>
              <div className='flex flex-col items-start justify-center w-full space-x-6 text-center lg:space-x-8 md:w-2/3 md:mt-0 md:flex-row md:items-center'>
                <Link href='/' passHref>
                  <a className='inline-block w-full py-2 mx-0 ml-6 font-medium text-left text-indigo-600 md:ml-0 md:w-auto md:px-0 md:mx-2 lg:mx-3 md:text-center'>
                    Home
                  </a>
                </Link>
                <Link href='/#wallets' passHref>
                  <a className='inline-block w-full py-2 mx-0 font-medium text-left text-gray-700 md:w-auto md:px-0 md:mx-2 hover:text-indigo-600 lg:mx-3 md:text-center'>
                    Support
                  </a>
                </Link>
                <Link href='/#faq' passHref>
                  <a className='inline-block w-full py-2 mx-0 font-medium text-left text-gray-700 md:w-auto md:px-0 md:mx-2 hover:text-indigo-600 lg:mx-3 md:text-center'>
                    FAQ
                  </a>
                </Link>
                <a
                  href='https://t.me/russianprotestdao'
                  target='_blank'
                  rel='noreferrer'
                  className='inline-block w-full py-2 mx-0 font-medium text-left text-gray-700 md:w-auto md:px-0 md:mx-2 hover:text-indigo-600 lg:mx-3 md:text-center'
                >
                  Telegram
                </a>
                <a
                  href='https://t.me/russianprotestdao'
                  target='_blank'
                  rel='noreferrer'
                  className='inline-block w-full py-2 mx-0 font-medium text-left text-gray-700 md:w-auto md:px-0 md:mx-2 hover:text-indigo-600 lg:mx-3 md:text-center'
                >
                  Twitter
                </a>
              </div>
            </div>
          </div>

          <div
            onClick={() => setIsOpen(!isOpen)}
            className='absolute right-0 flex flex-col items-center items-end justify-center w-10 h-10 bg-white rounded-full cursor-pointer md:hidden hover:bg-gray-100'
          >
            <svg
              className='w-6 h-6 text-gray-700'
              x-show='!showMenu'
              fill='none'
              strokeLinecap='round'
              strokeLineJoin='round'
              strokeWidth='2'
              viewBox='0 0 24 24'
              stroke='currentColor'
              x-cloak=''
            >
              <path d='M4 6h16M4 12h16M4 18h16'></path>
            </svg>
            <svg
              className='w-6 h-6 text-gray-700'
              x-show='showMenu'
              fill='none'
              stroke='currentColor'
              viewBox='0 0 24 24'
              xmlns='http://www.w3.org/2000/svg'
              x-cloak=''
            >
              <path
                strokeLinecap='round'
                strokeLineJoin='round'
                strokeWidth='2'
                d='M6 18L18 6M6 6l12 12'
              ></path>
            </svg>
          </div>
        </div>
      </nav>

      <section className='w-full px-6 pb-12 antialiased bg-white'>
        <div className='mx-auto max-w-7xl'>
          <div className='container max-w-lg px-4 py-32 mx-auto text-left md:max-w-none md:text-center'>
            <h1 className='text-5xl font-extrabold leading-10 tracking-tight text-left text-gray-900 md:text-center sm:leading-none md:text-6xl lg:text-7xl'>
              <span className='inline md:block'>Support Anti-Government</span>{' '}
              <span className='relative mt-2 text-transparent bg-clip-text bg-gradient-to-br from-indigo-600 to-indigo-500 md:inline-block'>
                Protests in Russia
              </span>
            </h1>
            <div className='mx-auto mt-5 text-gray-500 md:mt-12 md:max-w-lg md:text-center lg:text-lg'>
              {
                'Russian people need your support. All funds will be transferred to organisations fighting the regime, lawyers & protests'
              }
            </div>
            <div className='mx-auto mt-5 text-gray-900 font-bold md:mt-12 md:max-w-lg md:text-center lg:text-lg'>
              {'Peace to Ukraine. Freedom to Russia. Putin to prison'}
            </div>
            <div className='flex flex-col items-center mt-12 text-center'>
              <span className='relative inline-flex w-full md:w-auto'>
                <Link passHref href='/#wallets'>
                  <a
                    type='button'
                    className='inline-flex items-center justify-center w-full px-8 py-4 text-base font-bold leading-6 text-white bg-indigo-600 border border-transparent rounded-full md:w-auto hover:bg-indigo-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-600'
                  >
                    Support now
                  </a>
                </Link>
              </span>
            </div>
          </div>
        </div>
      </section>

      {/* WALLETS */}

      <section className='relative py-20 overflow-hidden bg-white' id='wallets'>
        <span className='absolute top-0 right-0 flex flex-col items-end mt-0 -mr-16 opacity-60'>
          <span className='container hidden w-screen h-32 max-w-xs mt-20 transform rounded-full rounded-r-none md:block md:max-w-xs lg:max-w-lg 2xl:max-w-3xl bg-blue-50'></span>
        </span>

        <span className='absolute bottom-0 left-0'> </span>

        <div className='relative px-16 mx-auto max-w-7xl'>
          <p className='font-medium tracking-wide text-blue-500 uppercase'>
            HOW TO SUPPORT
          </p>
          <div className='flex flex-col relative max-w-lg mt-5 mb-10 text-2xl font-semibold leading-tight lg:text-2xl'>
            You can contribute ETH, BTC, USDT to our DAO or you can donate to
            Ukrainian government
            <a
              target='__blank'
              className='py-2 text-indigo-400 hover:text-indigo-500 hover:underline'
              href='https://donate.thedigital.gov.ua/'
            >
              https://donate.thedigital.gov.ua/
            </a>
          </div>
          <div className='grid w-full grid-cols-2 gap-10 sm:grid-cols-3 lg:grid-cols-3'>
            <div className='flex flex-col items-center justify-center col-span-1'>
              <div className='relative p-5'>
                <img
                  src='https://www.bitcoinqrcodemaker.com/api/?style=ethereum&amp;address=0x38710865F709cd1E58C87ef8f8107ff5E64C9431'
                  alt='Ethereum QR Code Generator'
                  height='300'
                  width='300'
                  border='0'
                />
              </div>
              <div className='mt-3 space-y-2 text-center'>
                <div className='space-y-1 text-lg font-medium leading-6'>
                  <h3>ETH</h3>
                  <p className='text-blue-600 text-sm'>
                    0x38710865F709cd1E58C87ef8f8107ff5E64C9431
                  </p>
                </div>
              </div>
            </div>

            <div className='flex flex-col items-center justify-center col-span-1'>
              <div className='relative p-5'>
                <img
                  src='https://www.bitcoinqrcodemaker.com/api/?style=bitcoin&amp;address=bc1qxhh3sd04juefjttauhymlj8e6n6xcnwtawl9y3'
                  alt='Bitcoin QR Code Generator'
                  height='300'
                  width='300'
                  border='0'
                />
              </div>
              <div className='mt-3 space-y-2 text-center'>
                <div className='space-y-1 text-lg font-medium leading-6'>
                  <h3>BTC</h3>
                  <p className='text-blue-600 text-sm'>
                    bc1qxhh3sd04juefjttauhymlj8e6n6xcnwtawl9y3
                  </p>
                </div>
                <div className='relative flex items-center justify-center space-x-3'></div>
              </div>
            </div>

            <div className='flex flex-col items-center justify-center col-span-1'>
              <div className='relative p-5'>
                <img
                  src='https://www.bitcoinqrcodemaker.com/api/?style=ethereum&amp;address=0x38710865F709cd1E58C87ef8f8107ff5E64C9431'
                  alt='Ethereum QR Code Generator'
                  height='300'
                  width='300'
                  border='0'
                />
              </div>
              <div className='mt-3 space-y-2 text-center'>
                <div className='space-y-1 text-lg font-medium leading-6'>
                  <h3>USDT - ETH</h3>
                  <p className='text-blue-600 text-sm'>
                    0x38710865F709cd1E58C87ef8f8107ff5E64C9431
                  </p>
                </div>
              </div>
            </div>

            <div className='flex flex-col items-center justify-center col-span-1'>
              <div className='mt-3 space-y-2 text-center'>
                <div className='space-y-1 text-lg font-medium leading-6'>
                  <h3>USDT - TRC20</h3>
                  <p className='text-blue-600 text-sm'>
                    TR2gA6VrVK8eZZN8tfnx1TuBHhnaCWAWW7
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 'FAQ' */}

      <section
        id='faq'
        className='relative py-16 bg-white min-w-screen animation-fade animation-delay'
      >
        <div className='container px-0 px-8 mx-auto sm:px-12 xl:px-5'>
          <p className='text-sm font-bold text-left text-pink-500 uppercase sm:mx-6 sm:text-center sm:text-normal sm:font-bold'>
            Got a Question? We’ve got answers.
          </p>
          <h3 className='mt-1 text-2xl font-bold text-left text-gray-800 sm:mx-6 sm:text-3xl md:text-4xl lg:text-5xl sm:text-center sm:mx-0'>
            Frequently Asked Questions
          </h3>
          <div className='w-full px-6 py-6 mx-auto mt-10 bg-white border border-gray-200 rounded-lg sm:px-8 md:px-12 sm:py-8 sm:shadow lg:w-5/6 xl:w-2/3'>
            <h3 className='text-lg font-bold text-indigo-500 sm:text-xl md:text-2xl'>
              How can I help?
            </h3>
            <p className='mt-2 text-base text-gray-600 sm:text-lg md:text-normal'>
              You can fund our DAO to fight russian government in Russia. You
              can also visit{' '}
              <a
                href='https://war.ukraine.ua/'
                target='_blank'
                rel='noreferrer'
              >
                https://war.ukraine.ua/
              </a>
              to support the Ukrainain government!
            </p>
          </div>
          <div className='w-full px-6 py-6 mx-auto mt-10 bg-white border border-gray-200 rounded-lg sm:px-8 md:px-12 sm:py-8 sm:shadow lg:w-5/6 xl:w-2/3'>
            <h3 className='text-lg font-bold text-indigo-500 sm:text-xl md:text-2xl'>
              Where does the funds go?
            </h3>
            <p className='mt-2 text-base text-gray-600 sm:text-lg md:text-normal'>
              {
                'Currently there are thousands of protesters arrested across Russia and they need our help. The funds will go to lawyers in order to get as many protesters free as possible. By this we will send a clear message to the russian society that in case of arrest during a protest you will be covered. After this, we will fund protests and promote medias that tell the truth. First one is TV Rain who got shut down for speaking the truth.'
              }
            </p>
          </div>
          <div className='w-full px-6 py-6 mx-auto mt-10 bg-white border border-gray-200 rounded-lg sm:px-8 md:px-12 sm:py-8 sm:shadow lg:w-5/6 xl:w-2/3'>
            <h3 className='text-lg font-bold text-indigo-500 sm:text-xl md:text-2xl'>
              {"I don't have funds to support you, how else can I help?"}
            </h3>
            <p className='mt-2 text-base text-gray-600 sm:text-lg md:text-normal'>
              Promote our DAO. You can also visit IT Army of Ukraine on
              Telegram:
              <a
                className='text-indigo-400 hover:text-indigo-500 hover:underline'
                href='https://t.me/itarmyofukraine2022'
                target='_blank'
                rel='noreferrer'
              >
                https://t.me/itarmyofukraine2022
              </a>
            </p>
          </div>
        </div>
      </section>
      <section className='relative py-16 bg-white min-w-screen animation-fade animation-delay'>
        <div className='flex w-full justify-center items-center'>
          <h1 className='text-center font-bold text-indigo-500 text-2xl lg:text-4xl'>
            He is one. We are All.
          </h1>
        </div>
      </section>
    </div>
  );
}
